/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package carparkingmanagementsystemapp;

import javax.swing.JOptionPane;

/**
 *
 * @author siane
 */
public class AddVehicleGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AddVehicleGUI.class.getName());

    /**
     * Creates new form AddVehicleGUI
     */
    //variables
    private CarParkingManagementSystem cpms; //my parking management system
    
    public AddVehicleGUI(CarParkingManagementSystem cpms) { //want to keep the same one, not a blank empty one
        initComponents();
        this.cpms = cpms; //initialise it
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLBL = new javax.swing.JLabel();
        ownerNameLBL = new javax.swing.JLabel();
        ownerNameTF = new javax.swing.JTextField();
        licensePlateNumberLBL = new javax.swing.JLabel();
        licensePlateNumberTF = new javax.swing.JTextField();
        vehicleTypeLBL = new javax.swing.JLabel();
        vehicleTypeCBOX = new javax.swing.JComboBox<>();
        parkVehicleBTN = new javax.swing.JButton();
        backBTN = new javax.swing.JButton();
        exitBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleLBL.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        titleLBL.setText("Add a Vehicle");

        ownerNameLBL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ownerNameLBL.setText("Owner Name:");

        licensePlateNumberLBL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        licensePlateNumberLBL.setText("License Plate Number:");

        vehicleTypeLBL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        vehicleTypeLBL.setText("Vehicle Type:");

        vehicleTypeCBOX.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Car", "Electric Car", "Disabled Vehicle" }));

        parkVehicleBTN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        parkVehicleBTN.setText("Park Vehicle");
        parkVehicleBTN.addActionListener(this::parkVehicleBTNActionPerformed);

        backBTN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        backBTN.setText("Back");
        backBTN.addActionListener(this::backBTNActionPerformed);

        exitBTN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        exitBTN.setText("Exit");
        exitBTN.addActionListener(this::exitBTNActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addComponent(titleLBL))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(vehicleTypeLBL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(vehicleTypeCBOX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(licensePlateNumberLBL)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(licensePlateNumberTF))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(ownerNameLBL)
                                    .addGap(18, 18, 18)
                                    .addComponent(ownerNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(84, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(backBTN)
                .addGap(84, 84, 84)
                .addComponent(parkVehicleBTN)
                .addGap(56, 56, 56)
                .addComponent(exitBTN)
                .addGap(115, 115, 115))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLBL)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ownerNameLBL)
                    .addComponent(ownerNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(licensePlateNumberLBL)
                    .addComponent(licensePlateNumberTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vehicleTypeLBL)
                    .addComponent(vehicleTypeCBOX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(parkVehicleBTN)
                    .addComponent(backBTN)
                    .addComponent(exitBTN))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void parkVehicleBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parkVehicleBTNActionPerformed
        // TODO add your handling code here:
        //All the sections must be filled out in order to park a vehicle
        
        //variables
        String ownerName = ownerNameTF.getText();
        String licensePlateNumber = licensePlateNumberTF.getText();
        String vehicleType = vehicleTypeCBOX.getSelectedItem().toString(); //https://stackoverflow.com/questions/53977538/get-selected-item-on-jcombobox-java
                                                                           //turn to String
        //new Vehicle object
        Vehicle vehicle;
        
        //Checking if all the fields have been entered
        if(ownerName.isEmpty() || licensePlateNumber.isEmpty() || vehicleType.equals("Select")) {
            JOptionPane.showMessageDialog(null, "Please fill in all the fields providied to park your car");
        }
        
        //Checking the type entered and what objects to create
        if(vehicleType.equals("Car")) {
        vehicle = new Vehicle(ownerName, licensePlateNumber);
        }else if(vehicleType.equals("Electric Car")) {
            vehicle = new ElectricVehicle(ownerName, licensePlateNumber);
        }else {
            vehicle = new DisabledVehicle(ownerName, licensePlateNumber);
        }

        cpms.parkVehicle(vehicle);
        JOptionPane.showMessageDialog(null, "Vehicle Added");
    }//GEN-LAST:event_parkVehicleBTNActionPerformed

    private void backBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBTNActionPerformed
        // TODO add your handling code here:
        SmartParkGUI spGUI = new SmartParkGUI(cpms);
        spGUI.setVisible(true);
        dispose();
    }//GEN-LAST:event_backBTNActionPerformed

    private void exitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBTNActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new AddVehicleGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBTN;
    private javax.swing.JButton exitBTN;
    private javax.swing.JLabel licensePlateNumberLBL;
    private javax.swing.JTextField licensePlateNumberTF;
    private javax.swing.JLabel ownerNameLBL;
    private javax.swing.JTextField ownerNameTF;
    private javax.swing.JButton parkVehicleBTN;
    private javax.swing.JLabel titleLBL;
    private javax.swing.JComboBox<String> vehicleTypeCBOX;
    private javax.swing.JLabel vehicleTypeLBL;
    // End of variables declaration//GEN-END:variables
}
