/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package carparkingmanagementsystemapp;

/**
 *
 * @author siane
 */
public class SmartParkGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SmartParkGUI.class.getName());

    /**
     * Creates new form SmartParkGUI
     */
    //private data members
    private CarParkingManagementSystem cpms; //allowing the GUI to use my system
    
    public SmartParkGUI(CarParkingManagementSystem cpms) {
        initComponents();
        this.cpms = cpms; //initialising in the constructor
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLBL = new javax.swing.JLabel();
        addVehicleBTN = new javax.swing.JButton();
        removeVehicleBTN = new javax.swing.JButton();
        viewParkingBTN = new javax.swing.JButton();
        viewQueueBTN = new javax.swing.JButton();
        viewDisabledPQueueBTB = new javax.swing.JButton();
        viewParkingHistoryStackBTN = new javax.swing.JButton();
        exitBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleLBL.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        titleLBL.setText("SmartPark");

        addVehicleBTN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addVehicleBTN.setText("Add Vehicle");
        addVehicleBTN.addActionListener(this::addVehicleBTNActionPerformed);

        removeVehicleBTN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        removeVehicleBTN.setText("Remove Vehicle");
        removeVehicleBTN.addActionListener(this::removeVehicleBTNActionPerformed);

        viewParkingBTN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        viewParkingBTN.setText("View Parking");
        viewParkingBTN.addActionListener(this::viewParkingBTNActionPerformed);

        viewQueueBTN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        viewQueueBTN.setText("View Waiting List");
        viewQueueBTN.addActionListener(this::viewQueueBTNActionPerformed);

        viewDisabledPQueueBTB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        viewDisabledPQueueBTB.setText("View Disability Waiting List");
        viewDisabledPQueueBTB.addActionListener(this::viewDisabledPQueueBTBActionPerformed);

        viewParkingHistoryStackBTN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        viewParkingHistoryStackBTN.setText("View Parking History");
        viewParkingHistoryStackBTN.addActionListener(this::viewParkingHistoryStackBTNActionPerformed);

        exitBTN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        exitBTN.setText("Exit");
        exitBTN.addActionListener(this::exitBTNActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(278, 278, 278)
                        .addComponent(titleLBL))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(exitBTN))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(viewQueueBTN)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(viewParkingBTN)
                                    .addComponent(addVehicleBTN)
                                    .addComponent(viewDisabledPQueueBTB))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(85, 85, 85)
                                        .addComponent(viewParkingHistoryStackBTN))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(removeVehicleBTN)))))))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLBL)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addVehicleBTN)
                    .addComponent(removeVehicleBTN))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewParkingBTN)
                    .addComponent(viewQueueBTN))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewDisabledPQueueBTB)
                    .addComponent(viewParkingHistoryStackBTN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(exitBTN)
                .addGap(65, 65, 65))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addVehicleBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addVehicleBTNActionPerformed
        // TODO add your handling code here:
        //Go over to the AddVehicleGUI
        AddVehicleGUI avGUI = new AddVehicleGUI(cpms);
        avGUI.setVisible(true);
        dispose();
    }//GEN-LAST:event_addVehicleBTNActionPerformed

    private void exitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBTNActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitBTNActionPerformed

    private void removeVehicleBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeVehicleBTNActionPerformed
        // TODO add your handling code here:
        RemoveVehicleGUI rvGUI = new RemoveVehicleGUI(cpms);
        rvGUI.setVisible(true);
        dispose();
    }//GEN-LAST:event_removeVehicleBTNActionPerformed

    private void viewParkingBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewParkingBTNActionPerformed
        // TODO add your handling code here:
        ViewCarParkingSpacesGUI crpsGUI = new ViewCarParkingSpacesGUI(cpms);
        crpsGUI.setVisible(true);
        dispose();
    }//GEN-LAST:event_viewParkingBTNActionPerformed

    private void viewQueueBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewQueueBTNActionPerformed
        // TODO add your handling code here:
        WaitingListGUI wlGUI = new WaitingListGUI(cpms);
        wlGUI.setVisible(true);
        dispose();
    }//GEN-LAST:event_viewQueueBTNActionPerformed

    private void viewDisabledPQueueBTBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDisabledPQueueBTBActionPerformed
        // TODO add your handling code here:
        DisabilityWaitingListGUI dwlGUI = new DisabilityWaitingListGUI(cpms);
        dwlGUI.setVisible(true);
        dispose();
    }//GEN-LAST:event_viewDisabledPQueueBTBActionPerformed

    private void viewParkingHistoryStackBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewParkingHistoryStackBTNActionPerformed
        // TODO add your handling code here:
        CarParkingRecentHistoryGUI cprhGUI = new CarParkingRecentHistoryGUI(cpms);
        cprhGUI.setVisible(true);
        dispose();
    }//GEN-LAST:event_viewParkingHistoryStackBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new SmartParkGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addVehicleBTN;
    private javax.swing.JButton exitBTN;
    private javax.swing.JButton removeVehicleBTN;
    private javax.swing.JLabel titleLBL;
    private javax.swing.JButton viewDisabledPQueueBTB;
    private javax.swing.JButton viewParkingBTN;
    private javax.swing.JButton viewParkingHistoryStackBTN;
    private javax.swing.JButton viewQueueBTN;
    // End of variables declaration//GEN-END:variables
}
